const episodes = [
  { 
    id: 1,
    season: 1,
    episode: 1,
    name: 'Pilot',
    airdate: '10 January 1999',
    blurb: 'A mobster passes out at a family barbecue and seeks therapy to understand why.',
    characters: [1,2,3,4,5,6,7,8],
  },
  {
    id: 2,
    season: 1,
    episode: 2,
    name: '46 Long',
    airdate: '17 January 1999',
    blurb: `Tony is getting fed up with his mother. Brendan Filone acts against Tony's wishes. Salvatore and Paulie try to track down A.J.'s teacher's stolen car.`,
    characters: [1,2,3,4,5,6,7,8],
  },
  {
    id: 3,
    season: 1,
    episode: 3,
    name: 'Denial, Anger, Acceptance',
    airdate: '24 January 1999',
    blurb: `Tony encourages an unwanted son-in-law to divorce, Carmela learns another secret of Tony's, Meadow experiments with speed to study for the SATs, and Chris and Brendan find out the price of disrespecting Junior.`,
    characters: [1,2,3,4,5,6,7,8],
  },
  {
    id: 4,
    season: 1,
    episode: 4,
    name: 'Meadowlands',
    airdate: '31 January 1999',
    blurb: `Jackie's death leaves a power vacuum, Brendan's death leaves Chris fearing for his life, and Anthony's discovery of what his father really does leaves him confused.`,
    characters: [1,2,3,4,5,6,7,8],
  },
  {
    id: 5,
    season: 1,
    episode: 5,
    name: 'College',
    airdate: '7 February 1999',
    blurb: `While visiting colleges with Meadow, Tony spots a snitch. Carmela, meanwhile, discovers something about Dr. Melfi.`,
    characters: [1,2,3,5,7,8],
  },
  {
    id: 6,
    season: 1,
    episode: 6,
    name: 'Pax Soprana',
    airdate: '14 February 1999',
    blurb: `Tony tries to balance Junior against the other capos, while Carmela reasserts herself as the woman in Tony's life.`,
    characters: [1,2,3,8],
  },
  {
    id: 7,
    season: 1,
    episode: 7,
    name: 'Down Neck',
    airdate: '21 February 1999',
    blurb: `Anthony has disciplinary problems at school, prompting Tony to recount memories of his childhood with Dr. Melfi.`,
    characters: [1,2,3,4,5,7,8],
  },
  {
    id: 8,
    season: 1,
    episode: 8,
    name: 'The Legend of Tennessee Moltisanti',
    airdate: '28 February 1999',
    blurb: `The FBI begins closing in on the DiMeo family. Tony and Carmela are angry over all the attention Italians get from the authorities, while Chris fumes that he's not getting enough attention.`,
    characters: [1,2,3,4,5,6,7,8],
  },
  {
    id: 9,
    season: 1,
    episode: 9,
    name: 'Boca',
    airdate: '7 March 1999',
    blurb: `The capos discuss what to do about the local soccer coach, while Junior's mouth causes him some embarrassment.`,
    characters: [1,2,3,4,5,6,7,8],
  },
  {
    id: 10,
    season: 1,
    episode: 10,
    name: 'A hit is a hit',
    airdate: '14 March 1999',
    blurb: `Tony tries to branch out into legitimate investments, while Chris and Adriana decide to try their hands at music production.`,
    characters: [1,2,3,4,6,7,8],
  },
]

const characters = [
  {
    id: 1,
    name: 'Tony Soprano',
    actor: 'James Gandolfini',
    episodes: [1,2,3,4,5,6,7,8,9,10],
  },
  {
    id: 2,
    name: 'Carmela Soprano',
    actor: 'Edie Falco',
    episodes: [1,2,3,4,5,6,7,8,9,10],
  },
  {
    id: 3,
    name: 'Christopher Moltisanti',
    actor: 'Michael Imperioli',
    episodes: [1,2,3,4,5,6,7,8,9,10],
  },
  {
    id: 4,
    name: 'Silvio Dante',
    actor: 'Steven Van Zandt',
    episodes: [1,2,3,4,7,8,9,10],
  },
  {
    id: 5,
    name: 'A.J. Soprano',
    actor: 'Robert Iler',
    episodes: [1,2,3,4,5,7,8,9],
  },
  {
    id: 6,
    name: 'Paulie Gualtieri',
    actor: 'Tony Sirico',
    episodes: [1,2,3,4,8,9,10],
  },
  {
    id: 7,
    name: 'Meadow Soprano',
    actor: 'Jamie-Lynn Sigler',
    episodes: [1,2,3,4,5,7,8,9,10],
  },
  {
    id: 8,
    name: 'Dr. Jennifer Melfi',
    actor: 'Lorraine Bracco',
    episodes: [1,2,3,4,5,6,7,8,9,10],
  },
]

module.exports = {
  episodes,
  characters,
}